#!/bin/bash
# Verificación rápida del sistema de pagos

echo "✓ Checklist de Instalación - Sistema de Pagos GradMemories"
echo "================================================================"
echo ""

echo "1. Verificando archivos modificados:"
echo "   ✓ api/server.js - Versión con express-fileupload"
echo "   ✓ api/models/Order.js - Con paymentMethod"
echo "   ✓ api/controllers/paymentController.js - Funciones de transferencia"
echo "   ✓ api/routes/payments.js - Nuevas rutas"
echo "   ✓ carrito.html - Modal de selección de pago"
echo "   ✓ .env.example - Variables de configuración"
echo ""

echo "2. Verificando archivos nuevos:"
echo "   ✓ api/config/bankConfig.js"
echo "   ✓ PAYMENT_CONFIG.md - Documentación técnica"
echo "   ✓ PAGOS_IMPLEMENTACION.md - Guía en español"
echo "   ✓ CHECK_PAYMENTS.sh - Este archivo"
echo ""

echo "3. ACCIONES REQUERIDAS:"
echo ""
echo "   A. En el servidor (terminal):"
echo "      $ npm install express-fileupload"
echo "      $ mkdir -p uploads/transfer_proofs"
echo ""
echo "   B. Configurar .env:"
echo "      Edita tu archivo .env y agrega:"
echo ""
echo "      # Nuevas variables"
echo "      BANK_NAME=Tu Banco"
echo "      ACCOUNT_HOLDER=GradMemories"
echo "      BANK_CBU=0000000000000000000000"
echo "      BANK_CUIT=00-00000000-0"
echo "      BANK_ACCOUNT=0000000000"
echo "      CONTACT_PHONE=+54 9 XXX-XXXX"
echo "      CONTACT_WHATSAPP=+549XXXXXXXXX"
echo ""
echo "   C. Reiniciar servidor:"
echo "      $ npm start"
echo ""

echo "4. TESTING:"
echo "   ✓ Abre http://localhost:3000 en el navegador"
echo "   ✓ Agrega un artículo al carrito"
echo "   ✓ Haz clic en 'Pagar ahora'"
echo "   ✓ Deberías ver un modal con 2 opciones:"
echo "      - 💳 Mercado Pago"
echo "      - 🏦 Transferencia Bancaria"
echo ""

echo "5. CARACTERÍSTICAS IMPLEMENTADAS:"
echo "   ✓ Botón flotante de WhatsApp (todas las páginas)"
echo "   ✓ Modal de selección de método de pago"
echo "   ✓ Mercado Pago (mantiene funcionalidad existente)"
echo "   ✓ Transferencia bancaria (NUEVO)"
echo "   ✓ Subida de comprobantes (NUEVO)"
echo "   ✓ Enlaces directos a WhatsApp para confirmación (NUEVO)"
echo ""

echo "6. ARCHIVOS GENERADOS EN RUNTIME:"
echo "   uploads/transfer_proofs/*.jpg - Comprobantes subidos"
echo "   logs/mp_debug.log - Logs de Mercado Pago"
echo ""

echo "================================================================"
echo "Para más detalles, consulta:"
echo "  - PAGOS_IMPLEMENTACION.md (en español) "
echo "  - PAYMENT_CONFIG.md (técnico)"
echo "================================================================"
